# config/settings.yaml
---
# Model Configuration
model:
  device: "cuda"  # "cuda", "cpu", or "auto"
  model_path: "models/rife_weights.pth"  # Path to pretrained weights
  precision: "float32"  # "float32" or "float16"

# Interpolation Settings
interpolation:
  target_fps: 60.0
  interpolation_factor: 2  # 2x, 3x, 4x frame rate increase
  temporal_consistency: true
  multi_scale: false

# Processing Configuration
processing:
  batch_size: 4
  max_resolution: [1920, 1080]
  memory_efficient: true
  num_workers: 4

# Output Settings
output:
  codec: "mp4v"  # "mp4v", "h264", "h265"
  quality: 23  # CRF value (lower = better quality)
  pixel_format: "yuv420p"

# Performance Settings
performance:
  enable_mixed_precision: true
  gradient_checkpointing: false
  compile_model: false  # PyTorch 2.0 compile

# Logging
logging:
  level: "INFO"  # "DEBUG", "INFO", "WARNING", "ERROR"
  log_file: "logs/framegen.log"
  progress_bar: true